include: "high_dim_input/data_setup.smk"
include: "high_dim_input/preprocessing.smk"
include: "high_dim_input/evaluate_exactgp.smk"
include: "high_dim_input/evaluate_dkl.smk"
include: "high_dim_input/evaluate_rgasp.smk"
include: "high_dim_input/evaluate_pca_rgasp.smk"
